export const JSON_FAILED = 'JSON_FAILED'
export const JSON_SUCCESS = 'JSON_SUCCESS'
export const JSON_FETCHING = 'JSON_FETCHING'

export const CAMERA_FETCHING = 'CAMERA_FETCHING'
export const CAMERA_SUCCESS = 'CAMERA_SUCCESS'
export const CAMERA_FAILED = 'CAMERA_FAILED'