require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'demo2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  target 'demo2Tests' do
    inherit! :complete
    # Pods for testing
  end

  
end

target 'demo2-tvOS' do
  # Pods for demo2-tvOS

  target 'demo2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
